// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: app/interfaces/grpc/proto/v1/address/address.proto

package address

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GuidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid string `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
}

func (x *GuidRequest) Reset() {
	*x = GuidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuidRequest) ProtoMessage() {}

func (x *GuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuidRequest.ProtoReflect.Descriptor instead.
func (*GuidRequest) Descriptor() ([]byte, []int) {
	return file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescGZIP(), []int{0}
}

func (x *GuidRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type TermRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term string `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Size int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	From int64  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *TermRequest) Reset() {
	*x = TermRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermRequest) ProtoMessage() {}

func (x *TermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermRequest.ProtoReflect.Descriptor instead.
func (*TermRequest) Descriptor() ([]byte, []int) {
	return file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescGZIP(), []int{1}
}

func (x *TermRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *TermRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TermRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

type AddressListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Address `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *AddressListResponse) Reset() {
	*x = AddressListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListResponse) ProtoMessage() {}

func (x *AddressListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListResponse.ProtoReflect.Descriptor instead.
func (*AddressListResponse) Descriptor() ([]byte, []int) {
	return file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescGZIP(), []int{2}
}

func (x *AddressListResponse) GetItems() []*Address {
	if x != nil {
		return x.Items
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AoGuid         string `protobuf:"bytes,2,opt,name=AoGuid,proto3" json:"AoGuid,omitempty"`
	AoLevel        string `protobuf:"bytes,3,opt,name=AoLevel,proto3" json:"AoLevel,omitempty"`
	ParentGuid     string `protobuf:"bytes,4,opt,name=ParentGuid,proto3" json:"ParentGuid,omitempty"`
	ShortName      string `protobuf:"bytes,5,opt,name=ShortName,proto3" json:"ShortName,omitempty"`
	FormalName     string `protobuf:"bytes,6,opt,name=FormalName,proto3" json:"FormalName,omitempty"`
	PostalCode     string `protobuf:"bytes,7,opt,name=PostalCode,proto3" json:"PostalCode,omitempty"`
	FullName       string `protobuf:"bytes,8,opt,name=FullName,proto3" json:"FullName,omitempty"`
	FullAddress    string `protobuf:"bytes,9,opt,name=FullAddress,proto3" json:"FullAddress,omitempty"`
	District       string `protobuf:"bytes,10,opt,name=District,proto3" json:"District,omitempty"`
	DistrictType   string `protobuf:"bytes,11,opt,name=DistrictType,proto3" json:"DistrictType,omitempty"`
	DistrictFull   string `protobuf:"bytes,12,opt,name=DistrictFull,proto3" json:"DistrictFull,omitempty"`
	Settlement     string `protobuf:"bytes,13,opt,name=Settlement,proto3" json:"Settlement,omitempty"`
	SettlementType string `protobuf:"bytes,14,opt,name=SettlementType,proto3" json:"SettlementType,omitempty"`
	SettlementFull string `protobuf:"bytes,15,opt,name=SettlementFull,proto3" json:"SettlementFull,omitempty"`
	Street         string `protobuf:"bytes,16,opt,name=Street,proto3" json:"Street,omitempty"`
	StreetType     string `protobuf:"bytes,17,opt,name=StreetType,proto3" json:"StreetType,omitempty"`
	StreetFull     string `protobuf:"bytes,18,opt,name=StreetFull,proto3" json:"StreetFull,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescGZIP(), []int{3}
}

func (x *Address) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Address) GetAoGuid() string {
	if x != nil {
		return x.AoGuid
	}
	return ""
}

func (x *Address) GetAoLevel() string {
	if x != nil {
		return x.AoLevel
	}
	return ""
}

func (x *Address) GetParentGuid() string {
	if x != nil {
		return x.ParentGuid
	}
	return ""
}

func (x *Address) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Address) GetFormalName() string {
	if x != nil {
		return x.FormalName
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Address) GetFullAddress() string {
	if x != nil {
		return x.FullAddress
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Address) GetDistrictType() string {
	if x != nil {
		return x.DistrictType
	}
	return ""
}

func (x *Address) GetDistrictFull() string {
	if x != nil {
		return x.DistrictFull
	}
	return ""
}

func (x *Address) GetSettlement() string {
	if x != nil {
		return x.Settlement
	}
	return ""
}

func (x *Address) GetSettlementType() string {
	if x != nil {
		return x.SettlementType
	}
	return ""
}

func (x *Address) GetSettlementFull() string {
	if x != nil {
		return x.SettlementFull
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetStreetType() string {
	if x != nil {
		return x.StreetType
	}
	return ""
}

func (x *Address) GetStreetFull() string {
	if x != nil {
		return x.StreetFull
	}
	return ""
}

var File_app_interfaces_grpc_proto_v1_address_address_proto protoreflect.FileDescriptor

var file_app_interfaces_grpc_proto_v1_address_address_proto_rawDesc = []byte{
	0x0a, 0x32, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x47,
	0x75, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x22, 0x49,
	0x0a, 0x0b, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x72,
	0x6d, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x40, 0x0a, 0x13, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x29, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xb3, 0x04, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6f, 0x47, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6f, 0x47, 0x75, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x6f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x6f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x47, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x47, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6f, 0x73,
	0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x75, 0x6c, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x46, 0x75, 0x6c, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x46, 0x75, 0x6c, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x74,
	0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53,
	0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x65, 0x74,
	0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x46,
	0x75, 0x6c, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x53, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x72,
	0x65, 0x65, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x72, 0x65, 0x65,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x18,
	0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x46, 0x75, 0x6c,
	0x6c, 0x32, 0xb0, 0x03, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x59, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x79, 0x47, 0x75, 0x69,
	0x64, 0x12, 0x17, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x47,
	0x75, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x7b, 0x67, 0x75, 0x69, 0x64, 0x7d, 0x12,
	0x71, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x54,
	0x65, 0x72, 0x6d, 0x12, 0x17, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x31,
	0x2e, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x2f, 0x7b, 0x74, 0x65, 0x72,
	0x6d, 0x7d, 0x12, 0x5f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x12, 0x6f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x42, 0x79, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x17, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x5f, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x2f, 0x7b, 0x74,
	0x65, 0x72, 0x6d, 0x7d, 0x42, 0x34, 0x5a, 0x32, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x74, 0x6f, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescOnce sync.Once
	file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescData = file_app_interfaces_grpc_proto_v1_address_address_proto_rawDesc
)

func file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescGZIP() []byte {
	file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescOnce.Do(func() {
		file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescData)
	})
	return file_app_interfaces_grpc_proto_v1_address_address_proto_rawDescData
}

var file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_interfaces_grpc_proto_v1_address_address_proto_goTypes = []interface{}{
	(*GuidRequest)(nil),         // 0: address_v1.GuidRequest
	(*TermRequest)(nil),         // 1: address_v1.TermRequest
	(*AddressListResponse)(nil), // 2: address_v1.AddressListResponse
	(*Address)(nil),             // 3: address_v1.Address
	(*empty.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_app_interfaces_grpc_proto_v1_address_address_proto_depIdxs = []int32{
	3, // 0: address_v1.AddressListResponse.items:type_name -> address_v1.Address
	0, // 1: address_v1.AddressHandler.GetByGuid:input_type -> address_v1.GuidRequest
	1, // 2: address_v1.AddressHandler.GetAddressByTerm:input_type -> address_v1.TermRequest
	4, // 3: address_v1.AddressHandler.GetAllCities:input_type -> google.protobuf.Empty
	1, // 4: address_v1.AddressHandler.GetCitiesByTerm:input_type -> address_v1.TermRequest
	3, // 5: address_v1.AddressHandler.GetByGuid:output_type -> address_v1.Address
	2, // 6: address_v1.AddressHandler.GetAddressByTerm:output_type -> address_v1.AddressListResponse
	2, // 7: address_v1.AddressHandler.GetAllCities:output_type -> address_v1.AddressListResponse
	2, // 8: address_v1.AddressHandler.GetCitiesByTerm:output_type -> address_v1.AddressListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_interfaces_grpc_proto_v1_address_address_proto_init() }
func file_app_interfaces_grpc_proto_v1_address_address_proto_init() {
	if File_app_interfaces_grpc_proto_v1_address_address_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TermRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_interfaces_grpc_proto_v1_address_address_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_interfaces_grpc_proto_v1_address_address_proto_goTypes,
		DependencyIndexes: file_app_interfaces_grpc_proto_v1_address_address_proto_depIdxs,
		MessageInfos:      file_app_interfaces_grpc_proto_v1_address_address_proto_msgTypes,
	}.Build()
	File_app_interfaces_grpc_proto_v1_address_address_proto = out.File
	file_app_interfaces_grpc_proto_v1_address_address_proto_rawDesc = nil
	file_app_interfaces_grpc_proto_v1_address_address_proto_goTypes = nil
	file_app_interfaces_grpc_proto_v1_address_address_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddressHandlerClient is the client API for AddressHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressHandlerClient interface {
	GetByGuid(ctx context.Context, in *GuidRequest, opts ...grpc.CallOption) (*Address, error)
	GetAddressByTerm(ctx context.Context, in *TermRequest, opts ...grpc.CallOption) (*AddressListResponse, error)
	GetAllCities(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AddressListResponse, error)
	GetCitiesByTerm(ctx context.Context, in *TermRequest, opts ...grpc.CallOption) (*AddressListResponse, error)
}

type addressHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressHandlerClient(cc grpc.ClientConnInterface) AddressHandlerClient {
	return &addressHandlerClient{cc}
}

func (c *addressHandlerClient) GetByGuid(ctx context.Context, in *GuidRequest, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := c.cc.Invoke(ctx, "/address_v1.AddressHandler/GetByGuid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressHandlerClient) GetAddressByTerm(ctx context.Context, in *TermRequest, opts ...grpc.CallOption) (*AddressListResponse, error) {
	out := new(AddressListResponse)
	err := c.cc.Invoke(ctx, "/address_v1.AddressHandler/GetAddressByTerm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressHandlerClient) GetAllCities(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AddressListResponse, error) {
	out := new(AddressListResponse)
	err := c.cc.Invoke(ctx, "/address_v1.AddressHandler/GetAllCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressHandlerClient) GetCitiesByTerm(ctx context.Context, in *TermRequest, opts ...grpc.CallOption) (*AddressListResponse, error) {
	out := new(AddressListResponse)
	err := c.cc.Invoke(ctx, "/address_v1.AddressHandler/GetCitiesByTerm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressHandlerServer is the server API for AddressHandler service.
type AddressHandlerServer interface {
	GetByGuid(context.Context, *GuidRequest) (*Address, error)
	GetAddressByTerm(context.Context, *TermRequest) (*AddressListResponse, error)
	GetAllCities(context.Context, *empty.Empty) (*AddressListResponse, error)
	GetCitiesByTerm(context.Context, *TermRequest) (*AddressListResponse, error)
}

// UnimplementedAddressHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedAddressHandlerServer struct {
}

func (*UnimplementedAddressHandlerServer) GetByGuid(context.Context, *GuidRequest) (*Address, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByGuid not implemented")
}
func (*UnimplementedAddressHandlerServer) GetAddressByTerm(context.Context, *TermRequest) (*AddressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressByTerm not implemented")
}
func (*UnimplementedAddressHandlerServer) GetAllCities(context.Context, *empty.Empty) (*AddressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCities not implemented")
}
func (*UnimplementedAddressHandlerServer) GetCitiesByTerm(context.Context, *TermRequest) (*AddressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCitiesByTerm not implemented")
}

func RegisterAddressHandlerServer(s *grpc.Server, srv AddressHandlerServer) {
	s.RegisterService(&_AddressHandler_serviceDesc, srv)
}

func _AddressHandler_GetByGuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressHandlerServer).GetByGuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address_v1.AddressHandler/GetByGuid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressHandlerServer).GetByGuid(ctx, req.(*GuidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressHandler_GetAddressByTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressHandlerServer).GetAddressByTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address_v1.AddressHandler/GetAddressByTerm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressHandlerServer).GetAddressByTerm(ctx, req.(*TermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressHandler_GetAllCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressHandlerServer).GetAllCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address_v1.AddressHandler/GetAllCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressHandlerServer).GetAllCities(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressHandler_GetCitiesByTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressHandlerServer).GetCitiesByTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address_v1.AddressHandler/GetCitiesByTerm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressHandlerServer).GetCitiesByTerm(ctx, req.(*TermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "address_v1.AddressHandler",
	HandlerType: (*AddressHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByGuid",
			Handler:    _AddressHandler_GetByGuid_Handler,
		},
		{
			MethodName: "GetAddressByTerm",
			Handler:    _AddressHandler_GetAddressByTerm_Handler,
		},
		{
			MethodName: "GetAllCities",
			Handler:    _AddressHandler_GetAllCities_Handler,
		},
		{
			MethodName: "GetCitiesByTerm",
			Handler:    _AddressHandler_GetCitiesByTerm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/interfaces/grpc/proto/v1/address/address.proto",
}
