project:
  prefix:
elastic:
  scheme: http
  host: localhost:9200
  sniff: false
  gzip: true
  username:
  password:
batch:
  size: 5000
directory:
  filePath: /home/inter/tmp/fias/
process:
  print: true
fiasApi:
  url: https://fias.nalog.ru/WebServices/Public/
logger:
  console:
    enable: true
    level: debug
    json: false
  file:
    enable: true
    level: info
    json: true
    path: ./log.log