version: '3.2'
services:
  fias:
    container_name: ${PROJECT_PREFIX}app
    volumes:
      - ./app/:/app
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    ports:
      - ${DOCKER_INTERFACE}:${DOCKER_GRPC_PORT}:${GRPC_PORT}
      - ${DOCKER_INTERFACE}:${DOCKER_GRPC_GATEWAY_PORT}:${GRPC_GATEWAY_PORT}
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
    driver: bridge