// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: app/interfaces/grpc/proto/version/version.proto

package version

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerVersion string `protobuf:"bytes,1,opt,name=ServerVersion,proto3" json:"ServerVersion,omitempty"`
	GrpcVersion   string `protobuf:"bytes,2,opt,name=GrpcVersion,proto3" json:"GrpcVersion,omitempty"`
	FiasVersion   string `protobuf:"bytes,3,opt,name=FiasVersion,proto3" json:"FiasVersion,omitempty"`
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interfaces_grpc_proto_version_version_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_app_interfaces_grpc_proto_version_version_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_app_interfaces_grpc_proto_version_version_proto_rawDescGZIP(), []int{0}
}

func (x *Version) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Version) GetGrpcVersion() string {
	if x != nil {
		return x.GrpcVersion
	}
	return ""
}

func (x *Version) GetFiasVersion() string {
	if x != nil {
		return x.FiasVersion
	}
	return ""
}

var File_app_interfaces_grpc_proto_version_version_proto protoreflect.FileDescriptor

var file_app_interfaces_grpc_proto_version_version_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x24, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x72, 0x70, 0x63, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x47, 0x72, 0x70,
	0x63, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x69, 0x61, 0x73,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x46,
	0x69, 0x61, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x54, 0x0a, 0x0e, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x10, 0x2e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x0a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x04, 0x12, 0x02, 0x2f, 0x2a,
	0x42, 0x31, 0x5a, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x63, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_interfaces_grpc_proto_version_version_proto_rawDescOnce sync.Once
	file_app_interfaces_grpc_proto_version_version_proto_rawDescData = file_app_interfaces_grpc_proto_version_version_proto_rawDesc
)

func file_app_interfaces_grpc_proto_version_version_proto_rawDescGZIP() []byte {
	file_app_interfaces_grpc_proto_version_version_proto_rawDescOnce.Do(func() {
		file_app_interfaces_grpc_proto_version_version_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_interfaces_grpc_proto_version_version_proto_rawDescData)
	})
	return file_app_interfaces_grpc_proto_version_version_proto_rawDescData
}

var file_app_interfaces_grpc_proto_version_version_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_interfaces_grpc_proto_version_version_proto_goTypes = []interface{}{
	(*Version)(nil),     // 0: version.Version
	(*empty.Empty)(nil), // 1: google.protobuf.Empty
}
var file_app_interfaces_grpc_proto_version_version_proto_depIdxs = []int32{
	1, // 0: version.VersionHandler.GetVersion:input_type -> google.protobuf.Empty
	0, // 1: version.VersionHandler.GetVersion:output_type -> version.Version
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_interfaces_grpc_proto_version_version_proto_init() }
func file_app_interfaces_grpc_proto_version_version_proto_init() {
	if File_app_interfaces_grpc_proto_version_version_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_interfaces_grpc_proto_version_version_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_interfaces_grpc_proto_version_version_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_interfaces_grpc_proto_version_version_proto_goTypes,
		DependencyIndexes: file_app_interfaces_grpc_proto_version_version_proto_depIdxs,
		MessageInfos:      file_app_interfaces_grpc_proto_version_version_proto_msgTypes,
	}.Build()
	File_app_interfaces_grpc_proto_version_version_proto = out.File
	file_app_interfaces_grpc_proto_version_version_proto_rawDesc = nil
	file_app_interfaces_grpc_proto_version_version_proto_goTypes = nil
	file_app_interfaces_grpc_proto_version_version_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VersionHandlerClient is the client API for VersionHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VersionHandlerClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Version, error)
}

type versionHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionHandlerClient(cc grpc.ClientConnInterface) VersionHandlerClient {
	return &versionHandlerClient{cc}
}

func (c *versionHandlerClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, "/version.VersionHandler/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionHandlerServer is the server API for VersionHandler service.
type VersionHandlerServer interface {
	GetVersion(context.Context, *empty.Empty) (*Version, error)
}

// UnimplementedVersionHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedVersionHandlerServer struct {
}

func (*UnimplementedVersionHandlerServer) GetVersion(context.Context, *empty.Empty) (*Version, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}

func RegisterVersionHandlerServer(s *grpc.Server, srv VersionHandlerServer) {
	s.RegisterService(&_VersionHandler_serviceDesc, srv)
}

func _VersionHandler_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionHandlerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/version.VersionHandler/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionHandlerServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _VersionHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "version.VersionHandler",
	HandlerType: (*VersionHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _VersionHandler_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/interfaces/grpc/proto/version/version.proto",
}
