// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: app/interfaces/grpc/proto/health/health.proto

package health

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Health struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uptime               int64   `protobuf:"varint,1,opt,name=Uptime,proto3" json:"Uptime,omitempty"`
	AllocatedMemory      float32 `protobuf:"fixed32,2,opt,name=AllocatedMemory,proto3" json:"AllocatedMemory,omitempty"`
	TotalAllocatedMemory float32 `protobuf:"fixed32,3,opt,name=TotalAllocatedMemory,proto3" json:"TotalAllocatedMemory,omitempty"`
	Goroutines           int32   `protobuf:"varint,4,opt,name=Goroutines,proto3" json:"Goroutines,omitempty"`
	GCCycles             uint32  `protobuf:"varint,5,opt,name=GCCycles,proto3" json:"GCCycles,omitempty"`
	NumberOfCPUs         int32   `protobuf:"varint,6,opt,name=NumberOfCPUs,proto3" json:"NumberOfCPUs,omitempty"`
	HeapSys              float32 `protobuf:"fixed32,7,opt,name=HeapSys,proto3" json:"HeapSys,omitempty"`
	HeapAllocated        float32 `protobuf:"fixed32,8,opt,name=HeapAllocated,proto3" json:"HeapAllocated,omitempty"`
	ObjectsInUse         uint64  `protobuf:"varint,9,opt,name=ObjectsInUse,proto3" json:"ObjectsInUse,omitempty"`
	OSMemoryObtained     float32 `protobuf:"fixed32,10,opt,name=OSMemoryObtained,proto3" json:"OSMemoryObtained,omitempty"`
}

func (x *Health) Reset() {
	*x = Health{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_interfaces_grpc_proto_health_health_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_app_interfaces_grpc_proto_health_health_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_app_interfaces_grpc_proto_health_health_proto_rawDescGZIP(), []int{0}
}

func (x *Health) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Health) GetAllocatedMemory() float32 {
	if x != nil {
		return x.AllocatedMemory
	}
	return 0
}

func (x *Health) GetTotalAllocatedMemory() float32 {
	if x != nil {
		return x.TotalAllocatedMemory
	}
	return 0
}

func (x *Health) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *Health) GetGCCycles() uint32 {
	if x != nil {
		return x.GCCycles
	}
	return 0
}

func (x *Health) GetNumberOfCPUs() int32 {
	if x != nil {
		return x.NumberOfCPUs
	}
	return 0
}

func (x *Health) GetHeapSys() float32 {
	if x != nil {
		return x.HeapSys
	}
	return 0
}

func (x *Health) GetHeapAllocated() float32 {
	if x != nil {
		return x.HeapAllocated
	}
	return 0
}

func (x *Health) GetObjectsInUse() uint64 {
	if x != nil {
		return x.ObjectsInUse
	}
	return 0
}

func (x *Health) GetOSMemoryObtained() float32 {
	if x != nil {
		return x.OSMemoryObtained
	}
	return 0
}

var File_app_interfaces_grpc_proto_health_health_proto protoreflect.FileDescriptor

var file_app_interfaces_grpc_proto_health_health_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xee, 0x02, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55,
	0x70, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f,
	0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12,
	0x32, 0x0a, 0x14, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x14, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x47, 0x6f, 0x72, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x43, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x47, 0x43, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x50, 0x55, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43,
	0x50, 0x55, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x70, 0x53, 0x79, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x48, 0x65, 0x61, 0x70, 0x53, 0x79, 0x73, 0x12, 0x24, 0x0a,
	0x0d, 0x48, 0x65, 0x61, 0x70, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x48, 0x65, 0x61, 0x70, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x49, 0x6e,
	0x55, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x49, 0x6e, 0x55, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x4f, 0x53, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x4f, 0x62, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x10, 0x4f, 0x53, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4f, 0x62, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x64, 0x32, 0x57, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x0f, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x09, 0x12, 0x07, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x42, 0x30, 0x5a, 0x2e,
	0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_interfaces_grpc_proto_health_health_proto_rawDescOnce sync.Once
	file_app_interfaces_grpc_proto_health_health_proto_rawDescData = file_app_interfaces_grpc_proto_health_health_proto_rawDesc
)

func file_app_interfaces_grpc_proto_health_health_proto_rawDescGZIP() []byte {
	file_app_interfaces_grpc_proto_health_health_proto_rawDescOnce.Do(func() {
		file_app_interfaces_grpc_proto_health_health_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_interfaces_grpc_proto_health_health_proto_rawDescData)
	})
	return file_app_interfaces_grpc_proto_health_health_proto_rawDescData
}

var file_app_interfaces_grpc_proto_health_health_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_interfaces_grpc_proto_health_health_proto_goTypes = []interface{}{
	(*Health)(nil),      // 0: health.Health
	(*empty.Empty)(nil), // 1: google.protobuf.Empty
}
var file_app_interfaces_grpc_proto_health_health_proto_depIdxs = []int32{
	1, // 0: health.HealthHandler.CheckHealth:input_type -> google.protobuf.Empty
	0, // 1: health.HealthHandler.CheckHealth:output_type -> health.Health
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_interfaces_grpc_proto_health_health_proto_init() }
func file_app_interfaces_grpc_proto_health_health_proto_init() {
	if File_app_interfaces_grpc_proto_health_health_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_interfaces_grpc_proto_health_health_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Health); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_interfaces_grpc_proto_health_health_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_interfaces_grpc_proto_health_health_proto_goTypes,
		DependencyIndexes: file_app_interfaces_grpc_proto_health_health_proto_depIdxs,
		MessageInfos:      file_app_interfaces_grpc_proto_health_health_proto_msgTypes,
	}.Build()
	File_app_interfaces_grpc_proto_health_health_proto = out.File
	file_app_interfaces_grpc_proto_health_health_proto_rawDesc = nil
	file_app_interfaces_grpc_proto_health_health_proto_goTypes = nil
	file_app_interfaces_grpc_proto_health_health_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HealthHandlerClient is the client API for HealthHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthHandlerClient interface {
	CheckHealth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Health, error)
}

type healthHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthHandlerClient(cc grpc.ClientConnInterface) HealthHandlerClient {
	return &healthHandlerClient{cc}
}

func (c *healthHandlerClient) CheckHealth(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Health, error) {
	out := new(Health)
	err := c.cc.Invoke(ctx, "/health.HealthHandler/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthHandlerServer is the server API for HealthHandler service.
type HealthHandlerServer interface {
	CheckHealth(context.Context, *empty.Empty) (*Health, error)
}

// UnimplementedHealthHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedHealthHandlerServer struct {
}

func (*UnimplementedHealthHandlerServer) CheckHealth(context.Context, *empty.Empty) (*Health, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}

func RegisterHealthHandlerServer(s *grpc.Server, srv HealthHandlerServer) {
	s.RegisterService(&_HealthHandler_serviceDesc, srv)
}

func _HealthHandler_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthHandlerServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/health.HealthHandler/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthHandlerServer).CheckHealth(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _HealthHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "health.HealthHandler",
	HandlerType: (*HealthHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _HealthHandler_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/interfaces/grpc/proto/health/health.proto",
}
